export const categoryData = {
  category: [
    { label: "人物", value: "people" },
    { label: "石头/植物", value: "stone_plant" },
    { label: "生物结构", value: "biological_structure" },
    { label: "车辆", value: "vehicle" },
    { label: "微生物", value: "microorganism" },
    { label: "船舶", value: "ship" },
    { label: "飞机/航空器", value: "aircraft" },
    { label: "建筑", value: "architecture" },
    { label: "场景", value: "scene" },
    { label: "展台", value: "booth" },
    { label: "电商", value: "ecommerce" },
    { label: "舞美/会议", value: "stage_meeting" },
    { label: "武器", value: "weapon" },
    { label: "服装", value: "clothing" },
    { label: "雕塑/文物", value: "sculpture_relic" },
    { label: "家具", value: "furniture" },
    { label: "机械/器械", value: "machinery" },
    { label: "电子电器", value: "electronics" },
    { label: "食品/饮料/商品", value: "food_drink_goods" },
    { label: "生活用具", value: "household_tools" },
    { label: "游戏二维资源", value: "game_2d_resources" },
    { label: "坦克", value: "tank" },
    { label: "轿车", value: "car" },
    { label: "火车/轨道车", value: "train" },
    { label: "公交车", value: "bus" },
    { label: "自行车", value: "bicycle" },
    { label: "大卡车", value: "truck" },
    { label: "皮卡", value: "pickup" },
    { label: "工程车", value: "construction_vehicle" },
    { label: "摩托车", value: "motorcycle" },
    { label: "越野车", value: "offroad_vehicle" },
    { label: "赛车/跑车", value: "race_car" },
    { label: "科幻车", value: "sci_fi_vehicle" },
    { label: "车辆部件", value: "vehicle_parts" },
    { label: "其他", value: "other" },
  ],
  format: [
    { label: ".obj/.mtl", value: "obj_mtl" },
    { label: ".fbx", value: "fbx" },
    { label: ".max", value: "max" },
    { label: ".ma/.mb", value: "ma_mb" },
    { label: ".c4d", value: "c4d" },
    { label: ".blend", value: "blend" },
    { label: ".usdz", value: "usdz" },
    { label: ".usd", value: "usd" },
    { label: ".stl", value: "stl" },
    { label: ".dwg", value: "dwg" },
    { label: ".stp", value: "stp" },
    { label: ".ige/igs/iges", value: "iges" },
    { label: ".3dm", value: "3dm" },
    { label: ".bip/ksp", value: "bip_ksp" },
    { label: "其他", value: "other" },
  ],
  sides: [
    { label: "5K以下", value: "5k_below" },
    { label: "5K-10K", value: "5k_10k" },
    { label: "10K-30K", value: "10k_30k" },
    { label: "30K-100K", value: "30k_100k" },
    { label: "100K以上", value: "100k_above" },
  ],
  wiring: [
    { label: "三角形", value: "triangle" },
    { label: "四边形", value: "quad" },
    { label: "N边形", value: "n_gon" },
    { label: "三角形+四边形", value: "triangle_quad" },
  ],
}
